/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easymartmanagement;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeString.toLowerCase;

/**
 *
 * @author Tafhim
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    Connection con;

    public LoginPage() {
        initComponents();
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/easymart");
            if (con != null) {
                System.out.println("connection establised");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error in connection", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtloginEmail = new textfield.TextField();
        txtLoginPassword = new textfield.PasswordField();
        LoginButton = new javax.swing.JButton();
        LoginClear = new javax.swing.JButton();
        LoginExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/black-friday-elements-assortment.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(140, 207, 207));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtloginEmail.setBackground(new java.awt.Color(255, 153, 51));
        txtloginEmail.setLabelText("Email");
        jPanel2.add(txtloginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 362, 68));

        txtLoginPassword.setBackground(new java.awt.Color(255, 153, 51));
        txtLoginPassword.setLabelText("Password");
        txtLoginPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginPasswordKeyPressed(evt);
            }
        });
        jPanel2.add(txtLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 362, 67));

        LoginButton.setBackground(new java.awt.Color(255, 153, 0));
        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 128, 44));

        LoginClear.setBackground(new java.awt.Color(255, 153, 0));
        LoginClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        LoginClear.setText("Clear");
        LoginClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginClearActionPerformed(evt);
            }
        });
        jPanel2.add(LoginClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 125, 44));

        LoginExit.setBackground(new java.awt.Color(255, 153, 0));
        LoginExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit small.png"))); // NOI18N
        LoginExit.setText("Exit");
        LoginExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginExitActionPerformed(evt);
            }
        });
        jPanel2.add(LoginExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 120, 44));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Login");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/black-friday-elements-assortment.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginSystem() {
        try {
            // TODO add your handling code here:
            String email = toLowerCase(txtloginEmail.getText());
            String password = txtLoginPassword.getText();
            String sql = "SELECT * FROM LOGINDATA WHERE EMAIL = '" + email + "' OR USERNAME = '"+ email + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            String pass = null;
            String role = null;
            String name = null;
            //String userName = null;
            while (rs.next()) {

                pass = rs.getString("PASSWORD");
                role = rs.getString("ROLE");
                name = rs.getString("NAME");
        //        userName = rs.getString("USERNAME");

            }
            System.out.println("button working");
            if (password.equals(pass) && role.equals("admin") ) {
                new Dashboard().setVisible(true);
                dispose();
                // JOptionPane.showMessageDialog(null, "Login successfull" , "Information", JOptionPane.INFORMATION_MESSAGE);
            } else if (password.equals(pass) && role.equals("cashier")) {
                new PlaceOrderFrame(name).setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "incorrect email/password", "Information", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex) {
            //  JOptionPane.showMessageDialog(null, "Login successfull" , "Information", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(ItemListFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        loginSystem();

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LoginExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_LoginExitActionPerformed

    private void LoginClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginClearActionPerformed
        // TODO add your handling code here:
        txtloginEmail.setText("");
        txtLoginPassword.setText("");
    }//GEN-LAST:event_LoginClearActionPerformed

    private void txtLoginPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginSystem();
        }

    }//GEN-LAST:event_txtLoginPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton LoginClear;
    private javax.swing.JButton LoginExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private textfield.PasswordField txtLoginPassword;
    private textfield.TextField txtloginEmail;
    // End of variables declaration//GEN-END:variables
}
