/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easymartmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeString.toLowerCase;

/**
 *
 * @author Tafhim
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    Connection con;

    public LoginPage() {
        initComponents();
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/easymart");
            if (con != null) {
                System.out.println("connection establised");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error in connection", JOptionPane.INFORMATION_MESSAGE);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        LoginClear = new javax.swing.JButton();
        LoginExit = new javax.swing.JButton();
        txtloginEmail = new textfield.TextField();
        txtLoginPassword = new textfield.PasswordField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 63, -1, -1));

        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 325, 128, 44));

        LoginClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        LoginClear.setText("Clear");
        getContentPane().add(LoginClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 325, 125, 44));

        LoginExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit small.png"))); // NOI18N
        LoginExit.setText("Exit");
        LoginExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginExitActionPerformed(evt);
            }
        });
        getContentPane().add(LoginExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 497, 120, 44));

        txtloginEmail.setBackground(new java.awt.Color(0, 153, 153));
        txtloginEmail.setLabelText("Email");
        getContentPane().add(txtloginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 156, 362, 68));

        txtLoginPassword.setBackground(new java.awt.Color(0, 153, 153));
        txtLoginPassword.setLabelText("Password");
        getContentPane().add(txtLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 242, 362, 67));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String email = toLowerCase(txtloginEmail.getText());
            String password = txtLoginPassword.getText();
            String sql = "SELECT * FROM LOGINDATA WHERE EMAIL = '" +email +"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            String pass = null;
            String role = null;
            String name = null;
            while(rs.next())
            {

                pass = rs.getString("PASSWORD");
                role = rs.getString("ROLE");
                name = rs.getString("NAME");
                

            }
            System.out.println("button working");
            if(password.equals(pass) && role.equals("admin"))
            {
                new Dashboard().setVisible(true);
                dispose();
               // JOptionPane.showMessageDialog(null, "Login successfull" , "Information", JOptionPane.INFORMATION_MESSAGE);
            }else if(password.equals(pass) && role.equals("cashier")){
                new PlaceOrderFrame(name).setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "incorrect email/password" , "Information", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex) {
          //  JOptionPane.showMessageDialog(null, "Login successfull" , "Information", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(ItemListFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LoginExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_LoginExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton LoginClear;
    private javax.swing.JButton LoginExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private textfield.PasswordField txtLoginPassword;
    private textfield.TextField txtloginEmail;
    // End of variables declaration//GEN-END:variables
}
